//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishInABox.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FishWithTank
    {
        public double ID { get; set; }
        public string Species { get; set; }
        public Nullable<double> Stock_On_Hand { get; set; }
        public Nullable<double> Tank_Number { get; set; }
        public string Location { get; set; }
    }
}
