//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishInABox.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MARINE_SPECIES
    {
        public int ID_PK { get; set; }
        public int CLASS_FK { get; set; }
        public int SPECIES_FK { get; set; }
        public string SCIENTIFIC { get; set; }
        public string COMMON { get; set; }
        public string TEXT { get; set; }
        public Nullable<int> FAMILY_FK { get; set; }
    
        public virtual MARINE_CLASS MARINE_CLASS { get; set; }
        public virtual MARINE_FAMILY MARINE_FAMILY { get; set; }
    }
}
