//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishInABox.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MARINE_TYPE
    {
        public int ID_PK { get; set; }
        public string TEXT { get; set; }
        public string SCHEDULE3 { get; set; }
        public string SCHEDULE4 { get; set; }
    }
}
