//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishInABox.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECORD_PACKING
    {
        public int RECORD_FK { get; set; }
        public int BAG { get; set; }
        public int BOX { get; set; }
    
        public virtual PET_RECORD PET_RECORD { get; set; }
    }
}
