CREATE TABLE [dbo].[FISH_GENUS] (
    [ID_PK]       INT        IDENTITY (1, 1) NOT NULL,
    [COMMON]      NCHAR (25) NULL,
    [SCIENTIFIC]  NCHAR (25) NULL,
    [DESCRIPTION] NCHAR (50) NOT NULL,
    CONSTRAINT [PK_FISH_GENUS] PRIMARY KEY CLUSTERED ([ID_PK] ASC)
);

