CREATE TABLE [dbo].[FISH_IMAGE] (
    [FISH_FK] INT             NOT NULL,
    [IMAGE]   VARBINARY (MAX) NULL,
    CONSTRAINT [PK_FISH_IMAGE] PRIMARY KEY CLUSTERED ([FISH_FK] ASC),
    CONSTRAINT [FK_FISH_IMAGE_FISH] FOREIGN KEY ([FISH_FK]) REFERENCES [dbo].[FISH] ([ID_PK])
);

