CREATE TABLE [dbo].[FISH_FAMILY_OTHER_NAME] (
    [FAMILY_FK] INT        NOT NULL,
    [NAME]      NCHAR (25) NULL,
    CONSTRAINT [PK_FISH_FAMILY_OTHER_NAME] PRIMARY KEY CLUSTERED ([FAMILY_FK] ASC),
    CONSTRAINT [FK_FISH_FAMILY_OTHER_NAME_FISH_FAMILY] FOREIGN KEY ([FAMILY_FK]) REFERENCES [dbo].[FISH_FAMILY] ([ID_PK])
);

