CREATE TABLE [dbo].[FISH] (
    [ID_PK]       INT        IDENTITY (1, 1) NOT NULL,
    [DESCRIPTION] NCHAR (50) NULL,
    [CODE]        NCHAR (6)  NULL,
    [FAMILY_FK]   INT        NULL,
    [GENUS_FK]    INT        NULL,
    [COLOUR_FK]   INT        NULL,
    [SIZE_FK]     INT        NULL,
    CONSTRAINT [PK_FISH] PRIMARY KEY CLUSTERED ([ID_PK] ASC),
    CONSTRAINT [FK_FISH_FISH_COLOUR] FOREIGN KEY ([COLOUR_FK]) REFERENCES [dbo].[FISH_COLOUR] ([ID_PK]),
    CONSTRAINT [FK_FISH_FISH_FAMILY] FOREIGN KEY ([FAMILY_FK]) REFERENCES [dbo].[FISH_FAMILY] ([ID_PK]),
    CONSTRAINT [FK_FISH_FISH_GENUS] FOREIGN KEY ([GENUS_FK]) REFERENCES [dbo].[FISH_GENUS] ([ID_PK]),
    CONSTRAINT [FK_FISH_FISH_SIZE] FOREIGN KEY ([SIZE_FK]) REFERENCES [dbo].[FISH_SIZE] ([ID_PK])
);


GO
CREATE NONCLUSTERED INDEX [IX_FK_FISH_FISH_COLOUR]
    ON [dbo].[FISH]([COLOUR_FK] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_FK_FISH_FISH_FAMILY]
    ON [dbo].[FISH]([FAMILY_FK] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_FK_FISH_FISH_GENUS]
    ON [dbo].[FISH]([GENUS_FK] ASC);

