//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSED06_Aquatic_Pet_Store.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FIABEntities : DbContext
    {
        public FIABEntities()
            : base("name=FIABEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MARINE_FAMILY> MARINE_FAMILY { get; set; }
        public virtual DbSet<MARINE_TYPE> MARINE_TYPE { get; set; }
        public virtual DbSet<MARINE_CLASS> MARINE_CLASS { get; set; }
        public virtual DbSet<MARINE_SPECIES> MARINE_SPECIES { get; set; }
    }
}
